.PHONY: run-wasmparser-example run-wasmbin-example

run-wasmparser-test:
	cargo run --color=always test test_wasmbin src/wasm_circuit/wasm_parsers/tests/files/block_loop_local_vars.wat

run-wasmbin-test:
	cargo run --color=always test test_wasmbin src/wasm_circuit/wasm_parsers/tests/files/block_loop_local_vars.wat
